version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
      labels:
        com.host.description: "Janusly API Server"
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
  redis:
    image: redis:latest
  mysql:
    image: mysql:latest
    # MySQLの設定を追加
