version: '3.8'
services:
  api-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile
      labels:
        com.host.description: "Janusly API Server"
      target: builder
    volumes:
      - ./server:/app
    working_dir: /app
    # We need to use air to hot reload the server
    command: ["air", "-c", ".air.toml"]
    environment:
      # PORT Number for Gin
      - PORT=8080
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    depends_on:
      - dynamodb-local

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  dynamodb-admin:
    image: "aaronshaf/dynamodb-admin:4.6.1"
    container_name: dynamodb-admin
    ports:
      - target: 8001
        published: 8001
        protocol: tcp
        mode: host
    environment:
      DYNAMO_ENDPOINT: http://dynamodb-local:8000
    depends_on:
      - dynamodb-local
      # dynamodb-local:
      #   condition: service_healthy

  redis:
    image: redis:latest

  mysql:
    image: mysql:latest
    # MySQLの設定を追加

volumes:
  dynamodb_data:
