# .air.toml
root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # Build command
  cmd = "go build -o ./tmp/main ./cmd/api-server/main.go"
  # Executable file path after build
  bin = "./tmp/main"
  # Extensions of the files to watch
  include_ext = ["go", "tmpl", "html", "js", "css", "json"]
  # The directory where build will be triggered - we don't need to set this
  # include_dir = [""]
  # The directory to be ignored
  exclude_dir = ["assets", "tmp", "vendor", "bin"]


[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false
  # ログの時間フォーマット (例: 2006/01/02 - 15:04:05)
  time_format = "2006/01/02 - 15:04:05"

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true


# Command to be executed on hot reload
[cmd]
  # Command to be executed
  command = "./tmp/main"
  # File path that triggers hot reload
  include_dir = ["server"]
